-- AlterTable
ALTER TABLE "delegations" ADD COLUMN IF NOT EXISTS "start_time" VARCHAR(5) NOT NULL DEFAULT '09:00';
ALTER TABLE "delegations" ADD COLUMN IF NOT EXISTS "end_time" VARCHAR(5) NOT NULL DEFAULT '17:00';


